# Generated by Django 3.2.7 on 2021-09-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='This is the title', max_length=250),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
