# Generated by Django 3.2.7 on 2021-09-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
